### PR TITLE
Add ability to open mail apps without compose mode

### LINKED ISSUE #10: Open 3rd party app without composing
Is there a way to open a 3rd party app without composing an email? For instances where you want to help the user open the app to check their email (i.e. confirming a link, code, etc.)

### PR DESCRIPTION
**Pull request by angeria**
Closes #10

### CODE REVIEW

**Comment by vtourraine** [comment]
Hello Benjamin, and thanks a lot for sending this pull request!

I think we can significantly simplify this feature by generating the “open URL” directly from the existing `URLRoot` value. We just need to add a method on `ThirdPartyMailClient` to generate a URL with the [URL scheme](https://developer.apple.com/documentation/foundation/nsurl/1413437-scheme), and no host/path.

The other benefit is that it would fix the existing unit tests (they’re currently failing, because you’ve changed the `ThirdPartyMailClient` initializer). And, ideally, you would add a couple of unit tests to check the new “open URL”.

I hope this makes sense, and that you can find the time to update your pull request. I’ll be happy to merge it once this has been amended.

**Comment by angeria** [comment]
Sure, I could make that change! Do you mean the :// and :/// aren’t needed to open the apps (just e.g. `googlegmail`)? If they are there still has to be some switching on the clients since some need double brackets and some need tripple, right?

**Comment by vtourraine** [comment]
Only the URL scheme (the part before the `://`) is associated with a given app. So you just need the correct URL initializer, to avoid something like `googlegmail` becoming `http://googlegmail`. Maybe look at `NSURLComponents`?

**Comment by angeria** [comment]
Implementation is much cleaner now 🌿

**Comment by vtourraine** [comment]
Looking great! I’ve simply updated the unit tests to check this new “open URL”, and that’s it. I’ll merge the pull request, and push a new version in a couple of days.

Thanks for the contribution 👍

**Pull request merged**
