### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by imervich-globant**
I just created a new framework project (since I don't have access to the original one), added corresponding files and executed `carthage build --no-skip-current`.

Let me know if you have a better approach.

### CODE REVIEW

**Comment by vtourraine** [comment]
Hello Iván! Thank you very much for preparing this pull request, and sorry about being sooooo sloooooow to reply.

I’d be happy to add Carthage support. My only grip is that your pull request includes a lot of files in the `Carthage/Build` folder. I’ve never really used Carthage myself, so I could be wrong, but it seems like we don’t need those files, and I prefer to keep the library repository as clean as possible. Is it possible to remove them before we merge this in? Thanks in advance.

**Review by james1979-th — APPROVED** [review]

**Comment by imervich-globant** [comment]
Oh, sorry for the delay, I totally forgot about this!

This is also my first time adding Carthage support to a project and I only followed instructions on tutorials, which make me believe that folder is required in the repo. [Reference](https://medium.com/better-programming/how-to-create-a-framework-with-carthage-support-c30b596d3a7a)

If you or anyone else knows a better way to proceed, please let me know.

**Comment by vtourraine** [comment]
Cool! I’ve update the pull request to remove the “Build” files. Also, do we need to do something about this mention in `ThirdPartyMailer/ThirdPartyMailer.h`: 

```
// In this header, you should import all the public headers of your framework using statements like #import <ThirdPartyMailer/PublicHeader.h>
```

**Comment by imervich-globant** [comment]
> Cool! I’ve update the pull request to remove the “Build” files. Also, do we need to do something about this mention in `ThirdPartyMailer/ThirdPartyMailer.h`: 
> 
> 
> 
> ```
> 
> // In this header, you should import all the public headers of your framework using statements like #import <ThirdPartyMailer/PublicHeader.h>
> 
> ```

I don't think so. It's a preset comment for frameworks which use Objective-C.

**Comment by vtourraine** [comment]
Ok, great. I’ll merge it then, thanks a lot for sending the pull request!

**Pull request merged**
